#include "DDSXRCETypes.idl"

module eprosima {
module micrortps {

struct MessageHeader
{
    octet session_id;
    octet stream_id;
    unsigned short sequence_nr;
    eprosima::micrortps::ClientKey client_key;
};
};
};
