#include "DDSXRCETypes.idl"

module eprosima { module micrortps {

struct CREATE_CLIENT_Payload {
  BaseObjectRequest todo;
  OBJK_CLIENT_Representation object_representation;
};

struct CREATE_Payload {
  BaseObjectRequest todo;
  ObjectVariant object_representation;
};

struct DELETE_RESOURCE_Payload {
  BaseObjectRequest todo;
};

struct RESOURCE_STATUS_PAYLOAD {
  BaseObjectReply todo;
};

struct GET_INFO_Payload {
  BaseObjectRequest todo;
  InfoMask info_mask;
};

struct INFO_Payload {
  BaseObjectReply todo; // TODO(borja) ¿Esto hereda de BaseInfoReply?.
  Info info;            // TODO(borja) Posible error en el documento del estandard. Info esta definido pero no se usa en el payload.
};

struct READ_DATA_Payload {
  BaseObjectRequest todo;
  ReadSpecification read_specification;
};

struct DATA_Payload_Data {
  BaseObjectReply todo;
  SampleData data;
};

struct DATA_Payload_Sample {
  BaseObjectReply todo;
  Sample sample;
};

struct DATA_Payload_DataSeq {
  BaseObjectReply todo;
  sequence<SampleData> data_seq;
};

struct DATA_Payload_SampleSeq {
  BaseObjectReply todo;
  sequence<Sample> sample_seq;
};

struct DATA_Payload_PackedSamples {
  BaseObjectReply todo;
  PackedSamples packed_samples;
};

struct WRITE_DATA_Payload {
  BaseObjectRequest todo;
  DataRepresentation data_to_write;
};
};
};
